module WordGen::Modes
  NUMERIC = %w{1 2 3 4 5 6 7 8 9 0}
  LOWER = %w{a b c d e f g h i j k l m n o p q r s t u v w x y z}
  UPPER = %w{A B C D E F G H I J K L M N O P Q R S T U V W X Y Z}
  COMMON_SYBBOLS = %w{! ? $ # @}
  ALL_SYMBOLS = COMMON_SYBBOLS + %w{& % ^ * ( ) { } _ - + = | . ,}
  L_ALPHA_NUMERIC = LOWER + NUMERIC
  U_ALPHA_NUMERIC = UPPER + NUMERIC
  LCS_ALPHA_NUMERIC = LOWER + NUMERIC + COMMON_SYBBOLS
  UCS_ALPHA_NUMERIC = UPPER + NUMERIC + COMMON_SYBBOLS
  LS_ALPHA_NUMERIC = LOWER + NUMERIC + ALL_SYMBOLS
  US_ALPHA_NUMERIC = UPPER + NUMERIC + ALL_SYMBOLS
  ALL_COMMON_SYMBOLS = NUMERIC + LOWER + UPPER + COMMON_SYBBOLS
  ALL = NUMERIC + LOWER + UPPER + ALL_SYMBOLS
end
